<?php 
$_SESSION = json_decode('{
    "lang": "cs",
    "USER": {
        "id": 2,
        "username": "admin",
        "firstname": "Admin",
        "lastname": "User",
        "fullname": "Admin User",
        "email": "jorge.delgado86@gmail.com",
        "department": "",
        "institution": "Centro de Gesti\u00f3n",
        "firstaccess": 1415263413,
        "lastaccess": 1422356367,
        "description": "",
        "descriptionformat": 1,
        "city": "Valencia",
        "country": "ES",
        "profileimageurlsmall": "http:\/\/moodle.eformacion.gva.com\/pluginfile.php\/7\/user\/icon\/f2",
        "profileimageurl": "http:\/\/moodle.eformacion.gva.com\/pluginfile.php\/7\/user\/icon\/f1",
        "preferences": [{
            "name": "htmleditor",
            "value": ""
        }, {
            "name": "email_bounce_count",
            "value": "0"
        }, {
            "name": "email_send_count",
            "value": "1"
        }, {
            "name": "userselector_preserveselected",
            "value": "0"
        }, {
            "name": "userselector_autoselectunique",
            "value": "0"
        }, {
            "name": "userselector_searchanywhere",
            "value": "1"
        }, {
            "name": "filepicker_recentlicense",
            "value": "allrightsreserved"
        }, {
            "name": "theme_eves_full",
            "value": "nofull"
        }, {
            "name": "block4hidden",
            "value": "0"
        }, {
            "name": "block6hidden",
            "value": "1"
        }, {
            "name": "block5hidden",
            "value": "0"
        }, {
            "name": "block33hidden",
            "value": "0"
        }, {
            "name": "docked_block_instance_33",
            "value": "0"
        }, {
            "name": "scorm_report_detailed",
            "value": "0"
        }, {
            "name": "scorm_report_pagesize",
            "value": "20"
        }, {
            "name": "userselector_optionscollapsed",
            "value": "0"
        }, {
            "name": "message_provider_mod_quiz_confirmation_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_mod_quiz_confirmation_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_courserequestapproved_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_moodle_courserequestapproved_loggedoff",
            "value": "email"
        }, {
            "name": "auth_manual_passwordupdatetime",
            "value": "1418632309"
        }, {
            "name": "message_provider_moodle_courserequested_loggedin",
            "value": "email"
        }, {
            "name": "docked_block_instance_76",
            "value": "0"
        }, {
            "name": "message_provider_moodle_courserequested_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_courserequestrejected_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_moodle_courserequestrejected_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_errors_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_moodle_errors_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_enrol_self_expiry_notification_loggedin",
            "value": "email"
        }, {
            "name": "docked_block_instance_35",
            "value": "0"
        }, {
            "name": "message_provider_enrol_self_expiry_notification_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_enrol_manual_expiry_notification_loggedin",
            "value": "email"
        }, {
            "name": "login_failed_count_since_success",
            "value": "11"
        }, {
            "name": "message_provider_enrol_manual_expiry_notification_loggedoff",
            "value": "email"
        }, {
            "name": "block76hidden",
            "value": "0"
        }, {
            "name": "message_provider_mod_lesson_graded_essay_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_mod_lesson_graded_essay_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_instantmessage_loggedin",
            "value": "popup"
        }, {
            "name": "message_provider_moodle_instantmessage_loggedoff",
            "value": "popup,email"
        }, {
            "name": "message_provider_tool_messageinbound_invalidrecipienthandler_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_tool_messageinbound_invalidrecipienthandler_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_tool_messageinbound_messageprocessingerror_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_tool_messageinbound_messageprocessingerror_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_tool_messageinbound_messageprocessingsuccess_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_tool_messageinbound_messageprocessingsuccess_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_notices_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_moodle_notices_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_tool_monitor_notification_loggedin",
            "value": "email"
        }, {
            "name": "docked_block_instance_5",
            "value": "1"
        }, {
            "name": "message_provider_tool_monitor_notification_loggedoff",
            "value": "email"
        }, {
            "name": "docked_block_instance_4",
            "value": "1"
        }, {
            "name": "docked_block_instance_6",
            "value": "1"
        }, {
            "name": "message_provider_mod_assign_assign_notification_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_mod_assign_assign_notification_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_mod_quiz_attempt_overdue_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_mod_quiz_attempt_overdue_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_availableupdate_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_moodle_availableupdate_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_backup_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_moodle_backup_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_badgecreatornotice_loggedin",
            "value": "none"
        }, {
            "name": "message_provider_moodle_badgecreatornotice_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_moodle_badgerecipientnotice_loggedin",
            "value": "popup"
        }, {
            "name": "message_provider_moodle_badgerecipientnotice_loggedoff",
            "value": "popup,email"
        }, {
            "name": "message_provider_mod_forum_posts_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_mod_forum_posts_loggedoff",
            "value": "email"
        }, {
            "name": "message_provider_mod_quiz_submission_loggedin",
            "value": "email"
        }, {
            "name": "message_provider_mod_quiz_submission_loggedoff",
            "value": "email"
        }, {
            "name": "message_processor_email_email",
            "value": ""
        }, {
            "name": "message_blocknoncontacts",
            "value": "0"
        }, {
            "name": "message_beepnewmessage",
            "value": "1"
        }, {
            "name": "theme_squared_chosen_colpos",
            "value": "idock"
        }, {
            "name": "filepicker_recentrepository",
            "value": "4"
        }, {
            "name": "theme_eves_zoom",
            "value": "nozoom"
        }, {
            "name": "theme_bcu_zoom",
            "value": "nozoom"
        }, {
            "name": "theme_bcu_full",
            "value": "nofull"
        }, {
            "name": "_lastloaded",
            "value": 1422356633
        }]
    },
    "token": "e15feb66f472641491bda4b68b372be8"
}');
$_SESSION = (array)$_SESSION;